project:
  type: website

website:
  title: "Timothy M. Perez, PhD"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Code"
        href: code.qmd
      - text: "Research"
        href: research.qmd
      - text: "422"
        href: blog.qmd
    
      - icon: github
        href: https://github.com/tmoreperez
      - icon: twitter
        href: https://twitter.com/tmoreperez
      - icon: linkedin
        href: https://www.linkedin.com/in/timothymperez/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

editor: visual

